travis:
  secure:
    BINSTAR_TOKEN: EOsIZCHpwBZLvo+Q26ENo2n32MKrUe2eb+GYZVm477e0TlSp2fwftEVoByCTN+N8z7ZPh/QkqX8syoYx1LWp9dnFNrYPa8s4o7hGgUoxeDfwDaXWlKkIo7PR8+265NULRzFmf9TKcNRLY7qfhEPFJfiJevYPhSYaIsccuPsBXeTeZSuymZ7lBDHpH3ZFGMX9JX+UEU8gkPolhR/d7MhUBTAQu9t/wh7aAJPluMZ8C90nNynGFO7EpLvzEWYT1o/+m+ZieDUNIIjAnp7Flg3grDPXPu2QX04567EaCgcJJsRmBIMKyer0FeDi6h9F2oAmhpHR9J4sNpIymrr70Wkg6AWG6RwpfslOXcPfRJRqXpgh2u+vrKaX5obBHidxPJU+XITQxhO+lplo1ZyEZQLjENjLMv2xEel/ViQoujqtSFKHoBKkNyOcFaCTCa6UpldwRH+sGCgbXQ9/WpdzGOgYNHBya6I/xKnqE37y93Kf1KkioxWc06X0FLgyJaNvlIlOb4IGvPvpG+rReDy8o5XCyT0+dEcC8ylhsIWUofc3vMPdwzHg3uOTrGfFT7+VqE/EmKlVclXogVNjzrh1RH0/LDs1wOE/Y0il42LsEd3JGJn0vJcvcmmx+kkXEbVoPuvRymLZ0SD+I3HKfoy/78Jt1VMahixEdIPiDmGjzo7+5BU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
